export const rumorData = [
	{
		id: 'ebfd8ab3-d26a-4caa-b214-22ce203d4a73',
		name: 'Gandalf the Grey',
		content: 'Saw the player sneaking into the dungeon at night.',
		image_url: 'https://api.dicebear.com/9.x/pixel-art/svg?seed=1',
		like: 10,
		createAt: '2025-11-15T10:00:00Z',
	},
	{
		id: '93dd22f8-e13d-4618-ad5e-536f617c1d9a',
		name: 'Bob the Blacksmith',
		content: 'Heard the player broke the lock on the chest in the basement.',
		image_url: 'https://api.dicebear.com/9.x/pixel-art/svg?seed=2',
		like: 10,
		createAt: '2025-11-02T10:00:00Z',
	},
	{
		id: 'c0d6b71a-93d5-45df-99b3-1928f2de0ac1',
		name: 'Ella the Innkeeper',
		content: 'The player was seen leaving the inn in a hurry.',
		image_url: 'https://api.dicebear.com/9.x/pixel-art/svg?seed=3',
		like: 10,
		createAt: '2025-11-03T10:00:00Z',
	},
	{
		id: '87f0efa0-783d-4c31-94ef-1e5bd1d52f88',
		name: 'Marla the Herbalist',
		content: 'Claims the player bought a suspicious amount of nightshade.',
		image_url: 'https://api.dicebear.com/9.x/pixel-art/svg?seed=4',
		like: 10,
		createAt: '2025-11-04T10:00:00Z',
	},
	{
		id: '5116eb53-a17e-4b04-8608-78e82f461a85',
		name: 'Toren the Guard',
		content: 'Swears he saw the player jumping over the north gate at midnight.',
		image_url: 'https://api.dicebear.com/9.x/pixel-art/svg?seed=5',
		like: 10,
		createAt: '2025-11-05T10:00:00Z',
	},
	{
		id: '2a4f4c1b-5f3e-4d3b-9f7e-3c6e2b8f9d2c',
		name: 'Lena the Bard',
		content: 'Says the player paid her to sing a distracting song during a robbery.',
		image_url: 'https://api.dicebear.com/9.x/pixel-art/svg?seed=6',
		like: 10,
		createAt: '2025-11-06T10:00:00Z',
	},
	{
		id: '329b6f4e-8c4a-4f3a-9d2e-5f7b1c9e8a3f',
		name: 'Old Man Rurik',
		content: 'Believes the player is the chosen one destined to slay the Shadow Serpent.',
		image_url: 'https://api.dicebear.com/9.x/pixel-art/svg?seed=7',
		like: 10,
		createAt: '2025-11-07T10:00:00Z',
	},
	{
		id: 'd5f3c6e2b8f9d2c4a-4f3a-9d2e-5f7b1c9e8a3f',
		name: 'Sera the Merchant',
		content: 'Saw the player haggling for a cursed artifact.',
		image_url: 'https://api.dicebear.com/9.x/pixel-art/svg?seed=8',
		like: 10,
		createAt: '2025-11-08T10:00:00Z',
	},
	{
		id: 'ruik9876-5f3e-4d3b-9f7e-3c6e2b8f9d2c',
		name: 'Kelvin the Baker',
		content: 'Claims the player stole an entire tray of blueberry muffins at dawn.',
		image_url: 'https://api.dicebear.com/9.x/pixel-art/svg?seed=9',
		like: 10,
		createAt: '2025-11-09T10:00:00Z',
	},
	{
		id: 'dwq12345-5f3e-4d3b-9f7e-3c6e2b8f9d2c',
		name: 'Willa the Farmer',
		content: 'Says the player was talking to her chickens… and the chickens answered back.',
		image_url: 'https://api.dicebear.com/9.x/pixel-art/svg?seed=10',
		like: 10,
		createAt: '2025-11-10T10:00:00Z',
	},
];
export const rumorContents = [
	'Saw the player sneaking behind the old mill last night.',
	'Heard the player arguing with a mysterious hooded figure.',
	'The player was seen buying strange herbs from the herbalist.',
	'Someone claimed the player unlocked the forbidden gate.',
	'The player was spotted running across rooftops at dawn.',
	'Witnesses say the player bribed a town guard with gold.',
	'Heard rumors the player carries a cursed amulet.',
	'The innkeeper swears the player never sleeps in their room.',
	'Someone saw the player talking to shadows in the alley.',
	'The baker claims the player stole fresh bread at sunrise.',
	'Fishermen said the player summoned a fish out of thin air.',
	'A child says the player floated for a moment while walking.',
	'Merchants say the player paid with a coin from another realm.',
	'Reports say the player visited the abandoned lighthouse.',
	'A witness saw the player glowing faintly in the dark.',
	'The blacksmith claims the player bent steel with bare hands.',
	'The tailor said the player’s cloak repaired itself.',
	'Locals say the player disappeared for a full minute.',
	'A traveler saw the player talking to a ghost at midnight.',
	'Someone heard the player chanting ancient words.',
	'The librarian says the player checked out a forbidden tome.',
	'A guard swears the player outran a horse.',
	'Villagers say the player entered the cursed forest unharmed.',
	'Someone saw the player feeding a demon bird.',
	'The tavern keeper says the player never casts a shadow.',
	'A merchant heard the player speak in another language flawlessly.',
	'Rumor says the player found treasure under the fountain.',
	'The healer claims the player was poisoned but survived easily.',
	'Someone heard the player whisper to their weapon.',
	'An adventurer said the player defeated three bandits alone.',
	'The player was seen delivering a mysterious letter.',
	'A guard heard the player threaten the mayor quietly.',
	'Someone saw the player collecting rare mushrooms at night.',
	'A rumor says the player visited a hidden cave.',
	'A child claims the player summoned sparkles from thin air.',
	'The hunter said the player scared off wolves by staring at them.',
	'The player was seen counting gold coins rapidly.',
	'Villagers say the player can smell danger.',
	'The priest claims the player radiates unusual energy.',
	'Rumor says the player used magic in the marketplace.',
	'A trader saw the player vanish for a moment.',
	'A witness saw the player carrying a glowing crystal.',
	'Someone said the player talked to a talking cat.',
	'The fisherman claims the player walked on shallow water.',
	'A traveler heard the player humming a forbidden melody.',
	'The guard said the player dodged arrows effortlessly.',
	'Locals saw the player entering a secret passage.',
	'The player was seen carrying an ancient map.',
	'Someone heard the player negotiating with a troll.',
	'A child says the player turned invisible briefly.',
	'The baker claims the player never pays but food disappears.',
	'Rumor says the player can read minds.',
	'A wanderer says the player is protected by unseen forces.',
	'The apothecary claims the player survived a deadly potion.',
	'Someone saw the player talking to their reflection.',
	'A rumor says the player opened a sealed chest.',
	'The tailor claims the player’s clothes never get dirty.',
	'A farmer saw the player catch lightning in a bottle.',
	'A hunter says the player tamed a wild boar instantly.',
	'Someone said the player made a coin float.',
	'The innkeeper swears the player appeared out of thin air.',
	'Rumor says the player knows the king’s secret.',
	'A guard saw the player sneaking near the castle walls.',
	'The miner claims the player mined ore with bare hands.',
	'A witness saw the player running faster than wind.',
	'The bartender says the player never gets drunk.',
	'A rumor says the player talks to enchanted dolls.',
	'Someone saw the player open a magically sealed door.',
	'Villagers say the player survived a fall from a cliff.',
	'The scribe claims the player wrote in an ancient script.',
	'A hunter saw the player charm a snake.',
	'The tailor heard the player laugh at invisible jokes.',
	'A rumor says the player owns a forbidden artifact.',
	'Someone saw the player lift a boulder effortlessly.',
	'The apothecary swears the player healed instantly.',
	'A rumor says the player can see the future.',
	'The baker says the player ate ten pies alone.',
	'Villagers say the player walks without making sound.',
	'Someone saw the player whisper to a statue.',
	'The guard says the player slipped out of cuffs easily.',
	'A rumor says the player met the forest spirit.',
	'Fishermen say the player calmed a storm.',
	'The innkeeper says the player reserved a room but never stayed.',
	'Someone saw the player sprint across the riverbank.',
	'A traveler heard the player speak with animals.',
	'The tailor claims the player’s cloak floats slightly.',
	'A rumor says the player shut down a magical ward.',
	'A thief said the player caught him instantly.',
	'Locals saw the player sneaking behind the church.',
	'The priest claims the player glowed during prayer.',
	'Someone heard the player summon a small flame.',
	'The player was seen carrying a forbidden scroll.',
	'A rumor says the player never blinks.',
	'The hunter saw the player’s eyes turn bright red briefly.',
	'Villagers say the player’s shadow moves differently.',
];

export const npcNames = [
	'Alden the Wanderer',
	'Marla the Herbalist',
	'Toren the Guard',
	'Ella the Innkeeper',
	'Gandalf the Grey',
	'Bob the Blacksmith',
	'Sera the Merchant',
	'Lena the Bard',
	'Old Man Rurik',
	'Kelvin the Baker',
	'Willa the Farmer',
	'Joran the Carpenter',
	'Mira the Seamstress',
	'Ralph the Fisherman',
	'Yara the Hunter',
	'Thorin the Miner',
	'Elda the Fortune Teller',
	'Kael the Apprentice Mage',
	'Fiona the Druid',
	'Varin the Stable Master',
	'Silas the Mapmaker',
	'Odelia the Librarian',
	'Rowan the Ranger',
	'Nira the Alchemist',
	'Grim the Butcher',
	'Harold the Beekeeper',
	'Talia the Tailor',
	'Brynn the Scout',
	'Rux the Potion Brewer',
	'Felix the Cat Tamer',
	'Osric the Town Crier',
	'Milo the Tea Seller',
	'Hilda the Old Widow',
	'Caden the Inn Cook',
	'Finnian the Young Scribe',
	'Soren the Clockmaker',
	'Vera the Fortune Seeker',
	'Ravenna the Witch',
	'Perrin the Sheep Herder',
	'Juno the Herbal Collector',
	'Arlo the Wandering Monk',
	'Seraph the Priest',
	'Blaine the Leather Worker',
	'Dorian the Gem Trader',
	'Cassia the Spice Merchant',
	'Luther the Woodsman',
	'Ilya the Rune Reader',
	'Margo the Flower Seller',
	'Darius the Trainer',
	'Eris the Messenger',
	'Tessa the Scoutmaster',
	'Kellen the Watcher',
	'Rhea the Fisher Girl',
	'Briggs the Barrel Maker',
	'Ora the Storyteller',
	'Garrick the Mercenary',
	'Pippa the Acrobat',
	'Elric the Tinkerer',
	'Cyril the Bard',
	'Olwen the Healer',
	'Bram the Ale Brewer',
	'Nessa the Hunter’s Daughter',
	'Harmon the Goose Keeper',
	'Ivor the Guard Captain',
	'Marin the Mead Maker',
	'Tilda the Bread Vendor',
	'Quinn the Silent Monk',
	'Eamon the Cart Driver',
	'Sylvie the Artist',
	'Hawke the Tracker',
	'Malin the Fisher Queen',
	'Rurik the Elder',
	'Sable the Shadow Walker',
	'Orin the Candle Maker',
	'Jessa the Farmhand',
	'Calder the Spear Trainer',
	'Nikol the Story Keeper',
	'Yorin the Relic Seeker',
	'Maelis the Oracle',
	'Tovin the Shipwright',
	'Rika the Wolf Tamer',
	'Borin the Axemaster',
	'Selene the Moon Sage',
	'Gorge the Swamp Guide',
	'Adela the Fruit Seller',
	'Ronan the Stonemason',
	'Yvette the Weather Reader',
	'Torin the Shield Bearer',
	'Harlow the Falconer',
	'Faris the Trader',
	'Elowen the Mystic',
	'Gwen the Goat Herder',
	'Ulric the Drunk',
	'Peony the Gardener',
	'Jonah the Lost Knight',
	'Solin the Jeweler',
	'Drea the Candle Keeper',
	'Theron the Silent Hunter',
	'Marlowe the Lute Player',
];
