export const rumorData = [
		{
			name: 'Gandalf the Grey',
			content: 'Saw the player sneaking into the dungeon at night.',
			image_url: 'https://api.dicebear.com/9.x/pixel-art/svg?seed=1',
			like: 10,
			createAt: "2024-06-01T10:00:00Z",
		},
		{
			name: 'Bob the Blacksmith',
			content: 'Heard the player broke the lock on the chest in the basement.',
			image_url: 'https://api.dicebear.com/9.x/pixel-art/svg?seed=2',
			like: 10,
			createAt: "2024-06-02T10:00:00Z",
		},
		{
			name: 'Ella the Innkeeper',
			content: 'The player was seen leaving the inn in a hurry.',
			image_url: 'https://api.dicebear.com/9.x/pixel-art/svg?seed=3',
			like: 10,
			createAt: "2024-06-03T10:00:00Z",
		},
		{
			name: 'Marla the Herbalist',
			content: 'Claims the player bought a suspicious amount of nightshade.',
			image_url: 'https://api.dicebear.com/9.x/pixel-art/svg?seed=4',
			like: 10,
			createAt: "2024-06-04T10:00:00Z",
		},
		{
			name: 'Toren the Guard',
			content: 'Swears he saw the player jumping over the north gate at midnight.',
			image_url: 'https://api.dicebear.com/9.x/pixel-art/svg?seed=5',
			like: 10,
			createAt: "2024-06-05T10:00:00Z",
		},
		{
			name: 'Lena the Bard',
			content: 'Says the player paid her to sing a distracting song during a robbery.',
			image_url: 'https://api.dicebear.com/9.x/pixel-art/svg?seed=6',
			like: 10,
			createAt: "2024-06-06T10:00:00Z",
		},
		{
			name: 'Old Man Rurik',
			content: 'Believes the player is the chosen one destined to slay the Shadow Serpent.',
			image_url: 'https://api.dicebear.com/9.x/pixel-art/svg?seed=7',
			like: 10,
			createAt: "2024-06-07T10:00:00Z",
		},
		{
			name: 'Sera the Merchant',
			content: 'Saw the player haggling for a cursed artifact.',
			image_url: 'https://api.dicebear.com/9.x/pixel-art/svg?seed=8',
			like: 10,
			createAt: "2024-06-08T10:00:00Z",
		},
		{
			name: 'Kelvin the Baker',
			content: 'Claims the player stole an entire tray of blueberry muffins at dawn.',
			image_url: 'https://api.dicebear.com/9.x/pixel-art/svg?seed=9',
			like: 10,
			createAt: "2024-06-09T10:00:00Z",
		},
		{
			name: 'Willa the Farmer',
			content: 'Says the player was talking to her chickens… and the chickens answered back.',
			image_url: 'https://api.dicebear.com/9.x/pixel-art/svg?seed=10',
			like: 10,
			createAt: "2024-06-10T10:00:00Z",
		},
	]
