name: Build & Deploy Town Gossip Board

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pages: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Bun
              run: |
                  curl -fsSL https://bun.sh/install | bash
                  echo "$HOME/.bun/bin" >> $GITHUB_PATH

            - name: Install dependencies
              run: bun install

            - name: Build project
              run: bun run build

            - name: List dist files
              run: ls -l ./dist

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
                  publish_branch: gh-pages
